terriamap:
  image: rsignell/terria-usgs
  ports:
    - "3002:3001"
  container_name: terria
  volumes:
    - /opt/docker/terriamap/devserverconfig.json:/usr/local/app/TerriaMap/devserverconfig.json
    - /opt/docker/terriamap/config.json:/usr/local/app/TerriaMap/wwwroot/config.json
    - /opt/docker/terriamap/usgs.json:/usr/local/app/TerriaMap/wwwroot/init/usgs.json
